# This configuration aims at being a good setup
# for doing development of the frontend + backend in combination.

version: '3.6'

services:

  frontend:
    build:
      context: .
      dockerfile: frontend-dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend/public:/usr/src/app/frontend/public
      - ./frontend/src:/usr/src/app/frontend/src
      - ./frontend/theme:/usr/src/app/frontend/theme

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 5000:5000
    environment:
      - UVICORN_RELOAD=true
      - WEBVIZ_TENANT_ID
      - WEBVIZ_CLIENT_ID
      - WEBVIZ_CLIENT_SECRET
      - WEBVIZ_SUMO_RESOURCE_SCOPE
      - WEBVIZ_SMDA_RESOURCE_SCOPE
    volumes:
      - ./backend/src:/home/appuser/backend/src

  redis:
    image: "redis:alpine"
    command: redis-server
    expose:
      - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
  redis-conf:
