export enum CustomDataProviderType {
    OBSERVED_SURFACE = "OBSERVED_SURFACE",
    REALIZATION_GRID_2D = "REALIZATION_GRID_2D",
    RICH_DRILLED_WELL_TRAJECTORIES = "RICH_DRILLED_WELL_TRAJECTORIES",
}
