export enum DataProviderType {
    SUMMARY_VECTOR = "SUMMARY_VECTOR",
    SUMMARY_VECTOR_HISTORY = "SUMMARY_VECTOR_HISTORY",
    SUMMARY_VECTOR_OBSERVATIONS = "SUMMARY_VECTOR_OBSERVATIONS",
    INPLACE_VOLUMES = "INPLACE_VOLUMES",
}