import type { SurfaceMetaSet_api } from "@api";

import metadataJson from "../fixtures/surfaces/metadata.json" with { type: "json" };

/** Realization depth surfaces generated by backend_py/primary/scripts/generate_frontend_fixtures.py. */
export const SYNTH_SURFACE_METADATA = metadataJson as SurfaceMetaSet_api;

export const SYNTH_SURFACES = {
    names: SYNTH_SURFACE_METADATA.surface_names_in_strat_order,
    attribute: "depth",
    valueMin: Math.min(...SYNTH_SURFACE_METADATA.surfaces.map((surface) => surface.value_min ?? Infinity)),
    valueMax: Math.max(...SYNTH_SURFACE_METADATA.surfaces.map((surface) => surface.value_max ?? -Infinity)),
} as const;
